<?php 
$this->headTitle(' - Home');
$addJS = isset($this->addJS) ? $this->addJS.PHP_EOL : '';
$script = <<<EOT
$(document).ready(function(){
	$addJS		
$("#promotedDialog").dialog({
		autoOpen: false,
		height: 340,
		width: 500,
		modal: false,
		buttons: { "Close": function() { $(this).dialog("close"); } }
		});
		
	$('#whatisUpcoming').click(function() {
		//$('#dynamicLogin').dialog('open');
		$('#promotedDialog').dialog('open');
	});
	
});
EOT;

$this->headScript()->appendScript($script, $type = 'text/javascript', $attrs = array());

?>
<div id="promotedAndUpcoming" class="link">
	<?php foreach ($this->upcoming as $link):
	$linkBlab = $this->displayBlab($link->blabID, 1); // returns an array with [0] = blab title, [1] = anchor link to blab
	$linkURL = ($link->isSelf == 1) ? '/b/'.$linkBlab[0].'/comments/'.$link->id.'/'.$link->urlTitle : $link->linkurl;
 	?>	
<div class="link">
		<?php if ($this->loggedIn) {?>
			<?php echo $this->linkBuilder($link->id, $link->downvotes, $link->votes, $link->upvotes, true); ?>
		<?php } else {?>
		<div style="width: 5ex;" class="midcol unvoted">
			<a id="upcoming-link<?php echo $link->id; ?>-up" class="ui-state-default ui-corner-all" title="vote this link up" onclick="voteAction($(this), 1, <?php echo $link->id; ?>)"><span class="ui-icon ui-icon-circle-arrow-n"></span></a>
			<div class="score downVotes"><?php echo $link->downvotes; ?></div>
			<div class="score unVoted"><?php echo $link->votes; ?></div>
			<div class="score upVotes"><?php echo $link->upvotes; ?></div>
			<a id="upcoming-link<?php echo $link->id; ?>-down" class="ui-state-default ui-corner-all" title="vote this link down" onclick="voteAction($(this), 2, <?php echo $link->id; ?>)"><span class="ui-icon ui-icon-circle-arrow-s"></span></a>
		</div>
		<?php } if (!(is_null($link->thumbnail))) {?>
			<a name="linkblab_link-<?php echo $link->id; ?>" href="<?php echo $linkURL; ?>" class="thumbnail linkblab_link">&#8203;<img alt="" src="<?php echo $link->thumbnail; ?>" /></a>
		<?php }?>
		<div class="entry">
			<p class="title"><a name="linkblab_link<?php echo $link->id; ?>" href="<?php echo $linkURL; ?>" class="title linkblab_link"><?php echo $link->title; ?></a> 
			<span<?php echo ($link->isSelf == 1) ? ' style="display:none;"' : '' ?> class="domain">(<a title="see more links from this domain" href="/domain/<?php echo $link->domain; ?>/"><?php echo $link->domain; ?></a>)</span></p>	
			<p class="tagline">submitted <?php echo $this->timeAgo(strtotime($link->dateCreated));?> by <?php echo $this->displayName($link->userID, "autho user-".$link->userID); ?><span class="userattrs"></span> to <?php echo $linkBlab[1]; ?></p>
			<ul class="flat-list buttons">
				<?php if ($link->isNsfw == 1) {?>
				<li class="ui-corner-all nsfw-stamp stamp">
				<acronym title="Adult content: Not Safe For Work">NSFW</acronym></li>
				<?php } ?>
				<li class="first">
					<a target="_parent" href="/b/<?php echo $linkBlab[0].'/comments/'.$link->id.'/'.$link->urlTitle; ?>" class="comments"><?php echo $this->displayHowManyComments($link->id); ?> comments</a>
				</li>
				<li>
					<?php echo $this->buildReportButton($link->id); ?>
				</li>
			</ul>
		</div>
</div>
	<?php endforeach; ?>
<div class="nextprev">
	<img onclick="return get_organic(this, false)" alt="prev" src="/images/back_enabled.jpg">
	<img onclick="return get_organic(this, true)" alt="next" src="/images/forward_enabled.jpg">
</div>
<div class="help"><a href="javascript:void(0)" id="whatisUpcoming" class="open">what's this?</a></div>
</div>

<div id="linkList">
<?php 
	/*
	 * Properties of a link:
	protected $_linkurl;
	protected $_domain;
	protected $_thumbnail;
	protected $_upvotes;
	protected $_downvotes;
	protected $_votes;
	protected $_title;
	protected $_description;
	protected $_dateCreated;
	protected $_blabID;
	protected $_userID;
	protected $_isNsfw;
	protected $_isSelf;
	protected $_timesReported;
	protected $_controversy;
	protected $_id;
	*/
$i = 1;
if ($this->pagenumber > 1) {
$i = 1 + (25 * ($this->pagenumber -1));
}

foreach ($this->paginator as $link):
$linkBlab = $this->displayBlab($link->blabID, 1); // returns an array with [0] = blab title, [1] = anchor link to blab
$linkURL = ($link->isSelf == 1) ? '/b/'.$linkBlab[0].'/comments/'.$link->id.'/'.$link->urlTitle : $link->linkurl;
?>
<div class="link">
<span style="width: 2.2ex;" class="listNumber"><?php echo $i; ?></span>	
		<?php if ($this->loggedIn) {?>
			<?php echo $this->linkBuilder($link->id, $link->downvotes, $link->votes, $link->upvotes); ?>
		<?php } else {?>
		<div style="width: 5ex;" class="midcol unvoted">
			<a id="link<?php echo $link->id; ?>-up" class="ui-state-default ui-corner-all" title="vote this link up" onclick="voteAction($(this), 1, <?php echo $link->id; ?>)"><span class="ui-icon ui-icon-circle-arrow-n"></span></a>
			<div class="score downVotes"><?php echo $link->downvotes; ?></div>
			<div class="score unVoted"><?php echo $link->votes; ?></div>
			<div class="score upVotes"><?php echo $link->upvotes; ?></div>
			<a id="link<?php echo $link->id; ?>-down" class="ui-state-default ui-corner-all" title="vote this link down" onclick="voteAction($(this), 2, <?php echo $link->id; ?>)"><span class="ui-icon ui-icon-circle-arrow-s"></span></a>
		</div>
		<?php } if (!(is_null($link->thumbnail))) {?>
			<a name="linkblab_link-<?php echo $link->id; ?>" href="<?php echo $linkURL; ?>" class="thumbnail linkblab_link">&#8203;<img alt="<?php echo $link->urlTitle; ?>" src="<?php echo $link->thumbnail; ?>" /></a>
		<?php }?>
		<div class="entry">
			<p class="title"><a name="linkblab_link<?php echo $link->id; ?>" href="<?php echo $linkURL; ?>" class="title linkblab_link"><?php echo $link->title; ?></a> 
			<span<?php echo ($link->isSelf == 1) ? ' style="display:none;"' : '' ?> class="domain">(<a title="see more links from this domain" href="/domain/<?php echo $link->domain; ?>/"><?php echo $link->domain; ?></a>)</span></p>	
			<p class="tagline">submitted <?php echo $this->timeAgo(strtotime($link->dateCreated));?> by <?php echo $this->displayName($link->userID, "autho user-".$link->userID); ?><span class="userattrs"></span> to <?php echo $linkBlab[1]; ?></p>
			<ul class="flat-list buttons">
				<?php if ($link->isNsfw == 1) {?>
				<li class="ui-corner-all nsfw-stamp stamp">
				<acronym title="Adult content: Not Safe For Work">NSFW</acronym></li>
				<?php } ?>
				<li class="first">
					<a target="_parent" href="/b/<?php echo $linkBlab[0].'/comments/'.$link->id.'/'.$link->urlTitle; ?>" class="comments"><?php echo $this->displayHowManyComments($link->id); ?> comments</a>
				</li>
				<li>
					<?php echo $this->buildReportButton($link->id); ?>
				</li>
			</ul>
		</div>
</div>
<div class="clrLeft"></div>
<?php 
$i++;
endforeach; ?>
<?php 
echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>


<br />
<!-- Hidden Dialogs -->
<div id="promotedDialog" title="The Upcoming &amp; Promoted Section">
<p>The area at the top of the Linkblab.com homepage shows new and upcoming links. Vote on links here to help them become popular, and click the forwards and backwards buttons to view more.</p>
<p>
<a href="#">Click here</a> to disable this feature. <span style="display:none;">are you sure? yes / no</span>

</p>
</div>