<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Rich Editor</title>
  <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />
  <script type="text/javascript" src="/js/jquery-latest.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/js/markitup/skins/simple/style.css" />
  <link rel="stylesheet" type="text/css" href="/js/markitup/sets/bbcode/style.css" />
  
  <script type="text/javascript" src="/js/markitup/jquery.markitup.js"></script>
  <script type="text/javascript" src="/js/markitup/sets/bbcode/set.js"></script>
  <?php  // <link rel="stylesheet" href="/css/global.css" type="text/css" /> ?>  
  <link rel="stylesheet" href="/css/rich-edit.css" type="text/css" />
  <script type="text/javascript" src="/js/richEditor.js"></script>

</head>
<body>

<div id="formContainer">
<h2>LinkBlab Rich Text Editor</h2>

<form id="RichEditForm" name="richEditForm" method="POST" action="" onsubmit="return submitMe()">

<label for="comment">Comment</label>

<div class="spacer"> 
	<textarea id="comment" name="comment" rows="8" cols="10"></textarea>
</div>
<?php  /* 
<div id="contentPreview">
<label>Preview</label>
</div>
*/
?>

<div class="actionsBar">
	<button class="medium awesome" type="submit" value="">Submit &raquo;</button>
	<button onclick="return closeWindow()" class="small awesome orange" type="button" value="">Cancel Changes</button>
</div>

</form>


</div>

</body>

</html>