<?php 

$this->headTitle(' | Admin');
$this->headStyle()->appendStyle('@import "/css/table.css";');
$this->headScript()->appendFile("/js/jquery.uiforms.js", $type = 'text/javascript', $attrs = array());
$this->headScript()->appendFile("/js/admin.js", $type = 'text/javascript', $attrs = array());
$this->headScript()->appendFile("/js/jquery.dataTables.min.js", $type = 'text/javascript', $attrs = array());

?>
<style type="text/css">
    .auth-container {
        margin: 5px;
    }
    .auth-container h2 {
        text-align: center;
    }
    .responseMessage {
        font-weight: bold;
        color: fireBrick;
    }
</style>
<div class="auth-container">
    <h2>Admin Area</h2>
    <p>
        <?php
            if (isset($this->message)) {
                echo '<span class="responseMessage">'.nl2br($this->message).'</span>';
            }
        ?>
        <form method="POST">
            <label for="userId">Delete user(s) by id:</label>
            <input type="hidden" name="do" value="deleteUser" />
            <input id="userId" name="userId" type="text" placeholder="e.g. 1,3,4" />
            <input style="padding-right: 10px;" type="submit"></input>
        </form>
    </p>
    <h3>Current Users on Linkblab</h3>
     <?php 
	      $output = $this->userList();
	      if ($output !== false) {
	      ?>
	      <?php echo $output; 
	      }
	      ?>
	      
</div>