<?php 
$customSortPage = false;
if (strpos($this->url(), "index/controversial") !== false) {
	$customSortPage = true;
	$url = "/index/controversial";
}
else if (strpos($this->url(), "index/top") !== false) {
	$customSortPage = true;
	$url = "/index/top";
}
else if (strpos($this->url(), "/index") !== false) {
	$customSortPage = true;
	$url = "/index/hot";
}
?>
<div class="pagination">
    <div style="float:left;width:28%">
    </div>
    <div style="float:right;width:70%;margin:5px;">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array('page' => $this->first)); ?>">Start</a> |
        <?php else: ?>
                <span class="disabled">Start</span> |
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
            	<?php if (!$customSortPage): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                <?php else: ?>
                <a href="<?php echo $url."/page/".$page; ?>"><?php echo $page; ?></a>
                <?php endif; ?>
            <?php else: ?>
                <?php echo $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?php echo $this->url(array('page' => $this->next)); ?>">Next &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Next &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?php echo $this->url(array('page' => $this->last)); ?>">End</a>
        <?php else: ?>
            <span class="disabled">End</span>
        <?php endif; ?>
        &nbsp; Page <?php echo $this->current; ?> of <?php echo $this->last; ?>
    </div>
 </div>