<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />
  <link rel="stylesheet" href="/css/cupertino/jquery-ui-lastest.custom.css" type="text/css" />
  <script type="text/javascript" src="/js/jquery-latest.min.js"></script>
  <script src="/js/jquery-ui-latest.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="/js/jquery.linkselect.js"></script>
 <?php  // <script type="text/javascript" src="/js/jquery.bgiframe.js"></script> ?>
  <?php echo $this->headMeta()->appendName('keywords', 'framework, PHP, productivity').PHP_EOL; ?>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css').PHP_EOL; ?>
  <?php echo $this->headScript().PHP_EOL; ?>
  <?php echo $this->headTitle().PHP_EOL; ?>
  <?php echo $this->headStyle().PHP_EOL; 
  // USE A VIEW HELPER HERE TO ADD RSS FEEDS BASED ON ACTION
  ?>
  <script src="/js/jquery.defaultvalue.js" type="text/javascript"></script>  
  <?php 
  // Check if supported browser : I'd rather have them use  > IE8 
  ?>
  <script src="/js/jquery.badBrowser.js" type="text/javascript"></script>  
</head>
<body>
<div class="container">
   <div class="header">
       <div class="ui-corner-all" id="blabs">
	<span class="ui-corner-all" id="blabsTitle">Categories</span>
	<?php echo $this->buildBlabCategories(); ?>
	
	</div>
   		<a style="clear: right; display: inline;" title="linkblab home" href="/"><img src="/images/LinkBlab2.png"  alt="LinkBlab" name="LinkBlab" id="LinkBlabLogo" style="background: #8090AB; width: 255px;" /></a> 
    	<?php echo $this->buildBlabCategories('moreLink'); ?>
    <div id="loginMenu">
    <?php echo $this->loggedInAs(); ?>
    <form id="searchForm" action="/search" method="GET">
    <input name="q" id="search" type="text" />
    <input type="submit" value="Go" />
    </form>
    </div>
    <!-- end .header -->
    </div>
 	<div id="sidebar" class="sidebar1">
	<?php echo $this->buildSidebarContent(); ?>
	
	
	  
    <!-- end .sidebar1 -->
    </div>
 	<div class="content">
	<?php 
	// Create sorting options if this is a blab or home page:
	echo $this->buildSortingOptions();
	// Build Main Content Here
	echo $this->layout()->content ?>
	<!-- end .content --></div>
	 <div class="footer">
    <p style="text-align:center; color: #ffffff;"> &copy; <?php echo date("Y", time()); ?> <a href="http://www.kevinroberts.us">Kevin Roberts</a> <br /> Linkblab is yet another unabashed clone of <span class="reddit"><a href="http://www.reddit.com">Reddit</a></span> | experiment-ware | <a title="Written in PHP 5 using the Zend Framework" href="http://www.php.net"><img style="position: relative; top: 2px;" alt="written in PHP" src="/images/php5-power.png" /></a></p>
    <!-- end .footer --></div>
<!-- end .container --></div>
<div id="dynamicLogin" title="Login to Linkblab">
			<form id="dynamicLoginForm" action="/auth/login" method="post">
				<div id="dynamicLoginError">You must be logged in to vote! <a href="/auth/signup">sign up</a></div>
				<label for="dynUsername" class="uiforms-label">Username:</label>
				<input class="uiforms-input ui-state-default ui-corner-all uiforms-text" id="dynUsername" name="username" type="text" /> 
				<span id="usernameError"></span>
				<br />
				<label for="dynPassword" class="uiforms-label">Password:&nbsp;</label>
				<input class="uiforms-input ui-state-default ui-corner-all uiforms-text" id="dynPassword" name="password" type="password" />
				<span id="passwordError"></span>
				 <br />
				<input id="rememberMe" type="checkbox" value="1" name="rememberMe" />
				<label for="rememberMe" class="uiforms-label">Remember me? </label>
				<label class="tagline uiforms-label" style="cursor: text;">(persistant login - don't use on public computers)</label> 
				<input class="uiforms-input ui-state-default ui-corner-all uiforms-text" type="hidden" id="token" name="token" value="<?php echo $this->formToken();?>" />

			</form>
			<span style="float:right; padding-right: 101px; padding-top: 10px" id="ajaxLoader"><img alt="loading" src="/images/ajax-loader.gif" /> - Validating Credentials - <img alt="loading" src="/images/ajax-loader.gif" /></span>
</div>
</body>
</html>