<?php
$this->headTitle(' - '.$this->username."'s account");
$this->headStyle()->appendStyle('@import "/css/table.css";');
$this->headStyle()->appendStyle('@import "/css/user.css";');
$this->headScript()->appendFile("/js/user.js", $type = 'text/javascript', $attrs = array());
$this->headScript()->appendFile("/js/jquery.dataTables.min.js", $type = 'text/javascript', $attrs = array());
?>

<script type="text/javascript">
<!--
$(document).ready(function() {
	<?php if (!$this->postedResponse) { ?>
	    $("ul.tabs li:first").addClass("active").show(); //Activate first tab
	    $(".tab_content:first").show(); //Show first tab content
	<?php } else { ?>
	    $("ul.tabs li:eq(2)").addClass("active").show(); //Activate third tab
	    $(".tab_content:eq(2)").show(); //Show third tab content
	    $("#edit3").prepend('<div class="posted">Blabs updated succesfully</div>');
	    $('.posted').delay(500).effect('highlight');
	    $('.posted').delay(800).fadeOut();
	<?php } ?>
	
	$("#sortable").sortable({
		cursor: 'move',
		update : function () {
		serial = $('#sortable').sortable('serialize');
		$.ajax({
			url: "/user/ajaxhandler/token/<?php echo hash('sha256',$this->username.date('D', time() ).'SaK0fSa1t'); ?>/a/order/",
			type: "post",
			data: serial,
			beforeSend: function(){
			  $("#sortable").sortable("disable");
			  $("#loader").show();
			},
			error: function(){
			    alert("Server Error, Please try again later");
			},
		    success: function(data) {
				$("#loader").hide();
				$("#sortable").sortable("enable");
			    //alert(data);
			  }

			});
		}
		});
		
		$("#passwordUpdateFrm").submit( function(event) {
		    event.preventDefault();
			serial = $(this).serialize();
			valid = true;
			if ($("#newpass").val() != $("#verpass").val()) {
			    $("#verpass").effect('highlight', { color: "orange" }).next().show();
			    valid = false;
			}
			if ($("#curpass").val().length < 1) {
			    $("#curpass").effect('highlight', { color: "orange" }).next().show();
			    valid = false;
			}
			if (valid) {
    		    $.ajax({
    			    url: "/user/ajaxhandler/token/<?php echo hash('sha256',$this->username.date('D', time() ).'SaK0fSa1t'); ?>/a/changepassword/",
    			    type: "post",
    			    data: serial,
    			    beforeSend: function(){
    			        $("#loader2").show();
    			    },
    			    error: function(){
    			        alert("Server Error, Please try again later");
    			    },
    		        success: function(data) {
    				    $("#loader2").hide();
    				    $("#curpas, #verpass").next().hide();
    				    if (data == "Password changed") {
    				        $("#curpass, #newpass, #verpass").val("");
    				    }
    			        alert(data);
    			    }
    			    });
    			}

		} );
});
//-->
</script>
<div class="usernameHeader">
Account Management 
</div>

<?php if ($this->loggedIn) { ?>
<p>Welcome <?php echo $this->username; ?>: <a id="accountOptionsBtn" href="/user/<?php echo $this->username; ?>">Show my recent activity</a></p>

	<ul class="tabs">
	    <li><a href="#edit1">Change frontpage order</a></li>
	    <li><a href="#edit2">Edit Profile</a></li>
	    <li><a href="#edit3">Manage My Blabs</a></li>
	</ul>
	
	<div class="tab_container">
	    <div id="edit1" class="tab_content">
			<div class="frontpageOrder">
			<span id="loader">PLEASE WAIT<br />SAVING YOUR CHANGES<br /><img alt="loading" src="/images/ajax-loader2.gif" /></span>
			<p class="helptxt">Click and drag to reorder the sequence of blabs that appear on the upper navigation bar.</p>
			<ul id="sortable">
				<?php echo $this->accountEdit('frontpage', $this->userID); ?>
			</ul>

			</div><!-- End frontpageOrder -->
	         <p class="helptxt"><br />Want to subscribe to more Blab categories? <a href="/blabs">visit /blabs</a> and add some more to your front page!</p>
	      </div>
	    <div id="edit2" class="tab_content">
	        <div id="loader2">PLEASE WAIT<br />SAVING YOUR CHANGES<br /><img alt="loading" src="/images/ajax-loader2.gif" /></div>
	        <h3>Update your email or password</h3>
	         <form id="passwordUpdateFrm" action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
	         <label for="curpass">Current Password</label><br />
	         <input id="curpass" type="password" name="curpass" /><span class="ui-state-error" style="display:none; margin-left: 10px;">Current password is required.</span><br />
	         <label for="email">email</label><br />
	         <input id="email" type="text" value="<?php echo $this->email; ?>" name="email" /><br />
	         <label for="newpass">new password</label><br />
	         <input id="newpass" type="password" name="newpass"><br />
	         <label for="verpass">verify password</label><br />
	         <input id="verpass" type="password" name="verpass"><span class="ui-state-error" style="display:none; margin-left: 10px;">Verification password must equal new password.</span><br />
	         <br />
	         <button class="btn" type="submit">Save</button>
	         </form>
  
	    </div>
	    <div id="edit3" class="tab_content">
	     <h3>Manage Your Blab Categories</h3>

	      <?php 
	      $output = $this->accountEdit('blabs', $this->userID);
	      if ($output !== false) {
	      ?>
	      <form id="form" method="post" action="<?php echo $_SERVER['REQUEST_URI'];?>">
	      <div style="text-align: right; padding-bottom: 1em;">	
						<button type="submit">Submit Changes</button>
		  </div>	
	      <?php echo $output; ?>
	      <input type="hidden" id="unchecked" name="open" value="" />
	      </form> 
	      <?php } else { echo '<div style="margin: 10px auto 0pt; padding-top: 7px; width: 600px;" class="ui-state-highlight ui-corner-all"> 
					<p><span style="position: relative; float: left; left: 5px; top: -21px;" class="ui-icon ui-icon-info"></span>
					<strong style="">No Blabs!</strong> You dont have any Blabs to edit. Come back after you have created one.</p>
           </div>'.PHP_EOL;}  ?>
	    </div>
	</div>
	<br />	<br />




<?php } else {?>
<div class="usernameHeader">
<br />
You do not have the privileges to edit <?php echo $this->username;?>'s account.
</div>
<?php }?>